export const eventKeys = {
  clientId: 'Клиент',
  eventDate: 'Дата и время начала',
  dateEnd: 'Дата и время завершения',
  address: 'Адрес',
  status: 'Статус',
  servicesIds: 'Услуги',
  contractSum: 'Договорная сумма',
  description: 'Комментарий',
  additionalEvents: 'Доп. события',
  financeComment: 'Комментарий по финансам',
  invoiceLinks: 'Ссылки на счета',
  receiptLinks: 'Ссылки на чеки',
  isTransferred: 'Передано коллеге',
  colleagueId: 'Коллега',
  otherContacts: 'Прочие контакты',
  calendarImportChecked: 'Проверка мероприятия',
  calendarSyncError: 'Синхронизация календаря',
}

export const userKeys = {
  firstName: 'Имя',
  secondName: 'Фамилия',
  thirdName: 'Отчество',
  email: 'eMail',
  password: 'Пароль',
  images: 'Фотографии',
  gender: 'Пол',
  relationship: 'Статус отношений',
  personalStatus: 'Персональный статус',
  about: 'Обо мне',
  interests: 'Интересы',
  profession: 'Профессия',
  orientation: 'Ориентация',
  phone: 'Телефон',
  whatsapp: 'Whatsapp',
  viber: 'Viber',
  telegram: 'Telegram',
  instagram: 'Instagram',
  vk: 'ВКонтакте',
  birthday: 'День рождения',
  role: 'Роль',
  status: 'Статус в проекте',
  lastActivityAt: 'Время последней активности',
  prevActivityAt: 'Время предпоследней активности',
  archive: 'В архиве',
  haveKids: 'Есть дети',
  security: 'Настройки конфиденциальности',
  notifications: 'Настройки уведомлений',
  soctag: 'Социальный тэг',
  custag: 'Кастомный тэг',
}
